### ISSUE TITLE
Enabling additional relaxations in Rust causes executables to crash with Wild

### ISSUE THREAD

**Issue by mati865** [davidlattimore/wild#818]
I just learned about https://github.com/rust-lang/rust/issues/141720#issuecomment-2927684255 and gave it a try with Wild. Unfortunately, it causes almost 200 crashes in Rust testsuite (I excluded debuginfo tests): https://gist.github.com/mati865/0965760240f073618b8b2b0d7417fad1

Binaries fail like this:
- signal: 7, SIGBUS: access to undefined memory
- signal: 7 (SIGBUS) (core dumped)
- signal: 11 (SIGSEGV) (core dumped)
- signal: 11, SIGSEGV: invalid memory reference

Here is linker-diff comparison with LD for two tests: https://gist.github.com/mati865/1c7b74ddef351e7c3afa4d90c94de61f
(I can also provide the artifacts)

Repro steps:
1. Apply this diff::
```diff
diff --git a/compiler/rustc_target/src/spec/targets/x86_64_unknown_linux_gnu.rs b/compiler/rustc_target/src/spec/targets/x86_64_unknown_linux_gnu.rs
index 0c8353fad1..6181b7966f 100644
--- a/compiler/rustc_target/src/spec/targets/x86_64_unknown_linux_gnu.rs
+++ b/compiler/rustc_target/src/spec/targets/x86_64_unknown_linux_gnu.rs
@@ -19,6 +19,7 @@
         | SanitizerSet::SAFESTACK
         | SanitizerSet::THREAD;
     base.supports_xray = true;
+    base.relax_elf_relocations = true;

     // When we're asked to use the `rust-lld` linker by default, set the appropriate lld-using
     // linker flavor, and self-contained linker component.
```
2. Run Rust tests with Wild - this is not exactly straightforward. I had used https://github.com/mati865/wild-proxy via this config:
```toml
[rust]
default-linker = "/home/mateusz/Projects/wild-proxy/wild-cc"
lld = false
[target.x86_64-unknown-linux-gnu]
cc = "/home/mateusz/Projects/wild-proxy/wild-cc"
cxx = "/home/mateusz/Projects/wild-proxy/wild-c++"
linker = "/home/mateusz/Projects/wild-proxy/wild-cc"
```
